html разметка страницы формы
htmlacademy-adaptive/1282789-sedona-22 pull request #3
Opened 2021-04-01 18:22 UTC by iashchenkova

2021-04-04 08:20 UTC, radiogron commented on source/form.html
> +      <div class="main-nav__wrapper">
Не нужен.

2021-04-04 08:20 UTC, radiogron commented on source/form.html
> +  <main class="form-page">
Это больше служебный класс, смысловой. Вешать специфичный класс нет смысла, если не будет стилизации.

2021-04-04 08:20 UTC, radiogron commented on source/form.html
> +    <section class="review__intro">
А где родительский класс?

2021-04-04 08:20 UTC, radiogron commented on source/form.html
> +        <div>
Не нужен.

2021-04-04 08:20 UTC, radiogron commented on source/form.html
> +      <p> Помогите нашим отелям стать лучше! <br> оставьте отзыв о них, а также о <br> посещенных вами <br>
Убери пробел в начале.

2021-04-04 08:20 UTC, radiogron commented on source/form.html
> +          <label for="do-not-know">Затрудняюсь ответить</label>
Name-ы попутала.

2021-04-04 08:20 UTC, radiogron commented on source/form.html
> +          <label for="red-rocks">Красные скалы</label>
Name должен быть одинаковый.

2021-04-09 07:54 UTC, babtshe requested changes

2021-04-09 07:54 UTC, babtshe commented on source/form.html
> +            <a href="form.html">Форма отзыва</a>
страница не должна ссылаться сама на себя

2021-04-09 07:54 UTC, babtshe commented on source/form.html
> +            <a>Главная</a>
ссылки на главную не хватает.

2021-04-09 07:54 UTC, babtshe commented on source/form.html
> +    <button class="main-nav__toogle" type="button">
опечатка в названии класса

2021-04-09 07:54 UTC, babtshe commented on source/form.html
> +      <p>Помогите нашим отелям стать лучше! <br> оставьте отзыв о них, а также о <br> посещенных вами <br>
не стоит увлекаться `br`, см [критерий](https://up.htmlacademy.ru/adaptive/22/criteries#b2). Переносами текста можно управлять просто шириной контейнера, а от висящих предлогов хорошо спасает неразрывный пробел.

2021-04-09 07:54 UTC, babtshe commented on source/form.html
> +      <form method="GET" action="https://echo.htmlacademy.ru">
Есть смысл почитать про особенности GET и POST. Если в двух словах: для форм сборщиков контактов хорошо всегда использовать POST. Спроси меня почему, если не получится найти нужную инфу.

2021-04-09 07:54 UTC, babtshe commented on source/form.html
> +      <form method="GET" action="https://echo.htmlacademy.ru">
На самом деле форма на странице одна. Если для каждого поля будет отдельная форма - ничего не будет работать.

2021-04-09 07:54 UTC, babtshe commented on source/form.html
> +          <input type="text" id="phone" name="phone-number" placeholder="Введите телефон">
для телефона есть `type="tel"`, такой тип включает удобную клавиатуру на мобилках

2021-04-09 07:54 UTC, babtshe commented on source/form.html
> +          <input type="text" id="e-mail" name="e-mail" placeholder="Введите e-mail">
для почты тоже существует отдельный тип. Стоит использовать именно его, иначе не будет работать браузерное автозаполнение и минимальная валидация ввода.

2021-04-09 07:54 UTC, babtshe commented on source/form.html
> +          <label for="do-not-know">Затрудняюсь ответить</label>
было бы неплохо придумать более содержательные значения `value`. Иначе без залезания в исходный код невозможно понять, что это за значение.

2021-04-09 07:54 UTC, babtshe commented on source/form.html
> +            <a class="social__link social__link--twitter" href="#" target="blank">Twitter</a>
обрати внимание на синтаксис атрибута `target`

2021-04-09 07:54 UTC, babtshe commented on source/form.html
> +        <a class="copyright__link" href="#">html academy</a>
См. [ТЗ](https://up.htmlacademy.ru/adaptive/22/project/sedona#sedona-3-9)

2021-04-09 11:25 UTC, babtshe requested changes

2021-04-09 11:25 UTC, babtshe commented on source/form.html
> +            <a href="#">Форма отзыва</a>
`#` - эта штука обычно используется как заглушка, и говорит, что тут будет какая-то ссылка. При этом сама ссылка остаётся интерактивной и подсвечивается как активная. Лучше в таких случаях убирать `href` целиком.

2021-04-09 11:25 UTC, babtshe commented on source/form.html
> +      <form method="GET" action="https://echo.htmlacademy.ru">
Лишние формы стоит нещадно выпилить.

2021-04-09 11:25 UTC, babtshe commented on source/form.html
> +          <input type="radio" id="good" name="impressions" value="good-impression" checked>
стало лучше, и можно ещё улучшить, если избавиться от повторения названия параметра в его значении:
![image](https://user-images.githubusercontent.com/30229773/114173031-294f8a00-993f-11eb-84bc-8890577f5625.png)

2021-04-11 09:54 UTC, babtshe approved these changes

2021-04-11 09:54 UTC, merged