html разметка страницы каталога
htmlacademy-adaptive/1282789-sedona-22 pull request #4
Opened 2021-04-13 12:23 UTC by iashchenkova

2021-04-13 14:28 UTC, babtshe requested changes
перед отправкой на проверку стоит убедиться, что все тесты проходят. Если тесты красные - это гарантированная отправка домашки на доработку. 
![image](https://user-images.githubusercontent.com/30229773/114569180-6b4d3880-9c7d-11eb-8789-b12235a863f5.png)
Кстати, тесты можно запускать локально перед отправкой, чтобы не тратить время на экспериментальные коммиты.

2021-04-13 14:28 UTC, babtshe commented on source/catalog.html
> +    <a class="page-header__logo">
Стоит добавить ссылку на главную.

2021-04-13 14:28 UTC, babtshe commented on source/catalog.html
> +          <li class="site-list__item site-list__item--active">
на странице каталога будет другой активный элемент.

2021-04-13 14:28 UTC, babtshe commented on source/catalog.html
> +          <h3 class="photo__caption">Неродные просторы</h3>
обрати внимание на последовательность уровней заголовков.

2021-04-13 14:28 UTC, babtshe commented on source/catalog.html
> +    <h2>Все еще сомневаетесь? </h2>
Точно ли это заголовок?

2021-04-13 14:28 UTC, babtshe commented on source/catalog.html
> +      <source src="#">
тут нужны ещё элементы интерфейса, см [ТЗ](https://up.htmlacademy.ru/adaptive/22/project/sedona#sedona-6-2)

2021-04-13 15:40 UTC, iashchenkova commented on source/catalog.html
> +    <a class="page-header__logo">
сори! поторопилась и не заметила даже красный тест(
буду внимательнее

2021-04-14 06:35 UTC, babtshe approved these changes

2021-04-14 06:35 UTC, babtshe commented on source/catalog.html
> +        <a href="#"><img src="img/desert-flowers-sedona.jpg" width="280" height="280" alt="местная растительность"></a>
для чего здесь нужна ссылка?

2021-04-14 06:35 UTC, babtshe commented on source/catalog.html
> +      <video src="#" poster="img/video-poster.jpg" controls></video>
в ТЗ речь шла именно об отдельном проигрывателе видео. Стандартный проигрыватель не получится стилизовать под макет, поэтому будет нужна отдельная реализация.

2021-04-14 06:35 UTC, merged