less главная страница
htmlacademy-adaptive/1282789-sedona-22 pull request #5
Opened 2021-04-19 15:29 UTC by iashchenkova

2021-04-20 07:18 UTC, babtshe requested changes
Тесты продолжают падать из-за проблем с отступами. Хорошо будет перед отправкой на проверку запускать тесты локально и отправлять только когда ошибок больше не останется.
Большинство редакторов умеют подсвечивать отклонения от editorconfig в процессе работы без необходимости принудительного запуска тестов, но возможно придётся поставить плагин.

2021-04-20 07:18 UTC, babtshe commented on source/less/blocks/page-main.less
> +.advantages__intro h1 {
стоит избегать стилизации по тегам при использовании БЭМ и использовать классы.

2021-04-20 07:18 UTC, babtshe commented on source/less/global/fonts.less
> +  src: url("../../fonts/ptsans.woff2") format("woff2"),
сами шрифты неплохо было бы добавить в проект.

2021-04-20 08:27 UTC, iashchenkova commented on source/less/global/fonts.less
> +  src: url("../../fonts/ptsans.woff2") format("woff2"),
тэк, есть определенный затык
я не понимаю куда и как надо их добавить
и гугл мне не помогает, он предлагает сделать как я сделала и всё...
нет ли чего-нибудь подробного и пошагового почитать? 🔢

2021-04-20 08:32 UTC, iashchenkova commented on source/less/blocks/main-nav.less
> +}
над сделать отельный файл со ссылками имеется ввиду?

2021-04-20 08:36 UTC, iashchenkova commented on source/less/blocks/main-nav.less
> +}
имеется ввиду, что нужен для ссылок отдельный файл?

2021-04-20 13:52 UTC, babtshe requested changes

2021-04-20 13:52 UTC, babtshe commented on Readme.md
> +* Наставник: [Александр Бабченко] (https://htmlacademy.ru/profile/babtshe).
Хорошо бы проштудировать доку по [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet), сейчас ссылка выглядит так: 
![image](https://user-images.githubusercontent.com/30229773/115406860-3b131600-a1f8-11eb-82db-225f88c53831.png)

2021-04-20 13:52 UTC, babtshe commented on source/less/global/global.less
> +  list-style: none;
см [критерий](https://up.htmlacademy.ru/adaptive/22/criteries#d16)

2021-04-21 06:59 UTC, babtshe requested changes

2021-04-21 06:59 UTC, babtshe commented on source/less/blocks/page-footer.less
> +.social__item {
❗ см [критерий](https://up.htmlacademy.ru/adaptive/22/criteries#b13)

2021-04-21 06:59 UTC, babtshe commented on source/less/blocks/page-header.less
> +.site-list__item {
❗

2021-04-21 06:59 UTC, babtshe commented on source/less/blocks/page-main.less
>  .advantages-white__list {
❗

2021-04-21 06:59 UTC, babtshe commented on source/less/blocks/page.less
> +  font-family: "PT Sans", sans-serif;
см [критерий](https://up.htmlacademy.ru/adaptive/22/criteries#b10)

2021-04-23 07:32 UTC, babtshe requested changes

2021-04-23 07:32 UTC, babtshe commented on source/less/blocks/blue-block1.less
> +.advantages-town {
см предыдущий коммент. В целом не стоит использовать цифры в именах переменных без явной на то необходимости. Это ухудшает читаемость кода, так как не несёт никакой информации о содержимом этой переменной.

2021-04-24 07:09 UTC, babtshe requested changes

2021-04-24 07:09 UTC, babtshe commented on source/less/blocks/adavantages-number.less
> +.advantages__number {
`advantages` - это блок, ему нужен отдельный файл. А `number` - это элемент блока `advantages` они живут в одном файле. Делать отдельные файлы для каждого элемента - не нужно.

2021-04-24 07:09 UTC, babtshe commented on source/less/style.less
> +@import "blocks/advantages-white.less";
по сути эти изменения можно сделать через модификаторы, нет необходимости делать отдельный элемент для каждого.

2021-04-27 06:42 UTC, babtshe requested changes

2021-04-27 06:42 UTC, babtshe commented on source/less/blocks/advantages.less
> +.advantages-blue {
если записывать в таком виде, то это превращается в отдельный блок. Модификатор отделяется либо двойным дефисом, либо одинарным нижним подчёркиванием: `social__item--twitter`, `social__item_instagram`

2021-04-28 07:29 UTC, babtshe approved these changes

2021-04-28 07:30 UTC, merged